-- Zalo 管理后台数据表
-- 所有表 gmt_create / gmt_update 为 Zalo 源数据里的 CreatedAt/UpdatedAt
-- collected_at 为本地采集入库时间

CREATE TABLE IF NOT EXISTS zalo_account (
    id              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
    zalo_id         BIGINT       NOT NULL COMMENT 'Zalo 账号的后端 ID (对应 data[i].ID, 即 accountId)',
    account         VARCHAR(64)  NOT NULL COMMENT 'Zalo 手机号/账号',
    nick_name       VARCHAR(255)     NULL COMMENT '昵称',
    region          VARCHAR(16)      NULL COMMENT '区号 如 +84',
    password        VARCHAR(128)     NULL COMMENT '账号密码 (Zalo)',
    sex             INT              NULL COMMENT '0=未知 1=男 2=女',
    headimg         VARCHAR(512)     NULL COMMENT '头像 URL',
    online          INT              NULL COMMENT '在线状态 1=在线 2=离线',
    account_status  INT              NULL COMMENT '账号状态 1=正常',
    remark          VARCHAR(255)     NULL COMMENT '备注',
    proxy_ip        VARCHAR(255)     NULL COMMENT '代理 IP',
    proxy_id        BIGINT           NULL COMMENT '代理 ID',
    friends_sum     INT              NULL COMMENT '好友数',
    group_sum       INT              NULL COMMENT '群数',
    msg_sum         INT              NULL COMMENT '未读消息数',
    group_id        BIGINT           NULL COMMENT 'Zalo 分组 ID',
    group_name      VARCHAR(255)     NULL COMMENT 'Zalo 分组名',
    dept_id         BIGINT           NULL COMMENT '部门 ID',
    bind_id         BIGINT           NULL COMMENT '业务绑定 ID',
    sdbo            VARCHAR(64)      NULL COMMENT '生日字符串',
    wxid            VARCHAR(64)      NULL COMMENT 'wxid',
    is_shop         INT              NULL COMMENT '是否商铺',
    real_name       INT              NULL COMMENT '是否实名',
    create_by       VARCHAR(64)      NULL COMMENT 'Zalo 创建人',
    gmt_create      DATETIME(3)      NULL COMMENT 'Zalo 记录创建时间',
    gmt_update      DATETIME(3)      NULL COMMENT 'Zalo 记录更新时间',
    collected_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '本地入库时间',
    raw_json        LONGTEXT         NULL COMMENT '原始 JSON',
    deleted         TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '0=未删除 1=已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_zalo_id (zalo_id),
    KEY idx_account (account),
    KEY idx_nick_name (nick_name),
    KEY idx_dept_id (dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Zalo 账号信息 (WS code=1)';

CREATE TABLE IF NOT EXISTS zalo_friend (
    id               BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
    mongo_id         VARCHAR(64)      NULL COMMENT '后端 Mongo 文档 ID',
    owner_zalo_id    BIGINT       NOT NULL COMMENT '归属账号 (zalo_account.zalo_id)',
    owner_account    VARCHAR(64)      NULL COMMENT '归属账号手机号',
    friend_user_id   BIGINT       NOT NULL COMMENT '好友 Zalo userId (对端)',
    friend_uuid      BIGINT           NULL COMMENT 'info.uuid, 为 0 时是陌生人空壳',
    fstatus          INT              NULL COMMENT '0=陌生人 3=好友 5=非好友',
    remark           VARCHAR(255)     NULL COMMENT '备注',
    display_name     VARCHAR(255)     NULL COMMENT 'info.dpn 显示名',
    user_name        VARCHAR(128)     NULL COMMENT 'info.usr',
    avatar           VARCHAR(512)     NULL COMMENT 'info.avt',
    cover            VARCHAR(512)     NULL COMMENT 'info.cover',
    gender           INT              NULL COMMENT 'info.ged 0/1/2',
    phone            VARCHAR(32)      NULL COMMENT 'info.phone',
    status_text      VARCHAR(255)     NULL COMMENT 'info.stt',
    action_count     INT              NULL COMMENT 'info.ac',
    dept_id          BIGINT           NULL COMMENT '部门 ID',
    msg_sum          INT              NULL COMMENT '未读消息数',
    latest_msg_time  DATETIME(3)      NULL COMMENT '最后一条消息时间',
    gmt_create       DATETIME(3)      NULL COMMENT 'Zalo 记录创建时间',
    collected_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '本地入库时间',
    raw_json         LONGTEXT         NULL COMMENT '原始 JSON',
    deleted          TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '0=未删除 1=已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_owner_friend (owner_zalo_id, friend_user_id),
    KEY idx_friend_user_id (friend_user_id),
    KEY idx_display_name (display_name),
    KEY idx_fstatus (fstatus),
    KEY idx_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Zalo 好友列表 (WS code=7)';

CREATE TABLE IF NOT EXISTS zalo_message (
    id            BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
    mongo_id      VARCHAR(64)      NULL COMMENT '后端 Mongo 文档 ID',
    msg_id        BIGINT       NOT NULL COMMENT 'Zalo 原生 msgid',
    owner_zalo_id BIGINT       NOT NULL COMMENT '归属账号 (accountid)',
    owner_account VARCHAR(64)      NULL COMMENT '归属账号手机号',
    peer_user_id  BIGINT       NOT NULL COMMENT '对端 userId (fid)',
    group_id      BIGINT           NULL COMMENT '群 ID, 0 表示一对一',
    content       LONGTEXT         NULL COMMENT '消息内容',
    msg_type      INT              NULL COMMENT '1=文本 2=图片 3=语音 4=视频 5=系统 7=贴图 8=卡片',
    direction     INT              NULL COMMENT 'from 字段: 0=收 其他=发',
    is_send       INT              NULL COMMENT '0=对方发/已送达 1=发送中 2=失败',
    is_read       INT              NULL COMMENT '1=已读',
    seen          INT              NULL COMMENT '对端是否已读',
    nickname      VARCHAR(255)     NULL COMMENT '消息里的显示名',
    dst           TEXT             NULL COMMENT '翻译结果',
    describe_     VARCHAR(512)     NULL COMMENT '发送失败描述',
    bind_id       BIGINT           NULL COMMENT '业务绑定 ID',
    dept_id       BIGINT           NULL COMMENT '部门 ID',
    gmt_create    DATETIME(3)      NULL COMMENT 'Zalo 消息时间 CreatedAt',
    collected_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '本地入库时间',
    raw_json      LONGTEXT         NULL COMMENT '原始 JSON',
    deleted       TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '0=未删除 1=已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_msg (owner_zalo_id, peer_user_id, msg_id),
    KEY idx_msg_id (msg_id),
    KEY idx_owner (owner_zalo_id),
    KEY idx_peer (peer_user_id),
    KEY idx_gmt_create (gmt_create)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Zalo 聊天记录 (WS code=17)';

CREATE TABLE IF NOT EXISTS admin_user (
    id            BIGINT       NOT NULL AUTO_INCREMENT,
    username      VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(128) NOT NULL COMMENT 'BCrypt',
    nick_name     VARCHAR(128)     NULL,
    enabled       TINYINT(1)   NOT NULL DEFAULT 1,
    gmt_create    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    gmt_update    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='后台管理员';
